service: sigmund-blacklight-api

plugins:
  - serverless-prune-plugin
  # - serverless-bundle
  - serverless-webpack

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  profile: ${opt:profile, 'sigmund-profile'}

functions:
  # getBlackLightReport:
  #   handler: handler.main
  #   memorySize: 512 # optional, in MB, default is 1024
  #   timeout: 30 # optional, in seconds, default is 6
  #   events:
  #       - http:
  #           path: getBlackLightReport
  #           method: post
  #           cors: true
  todo-api:
    handler: tdcx-todos/handler.main
    events:
        - http:
            path: api/{proxy+}
            method: ANY
            cors: true

            
custom:
    prune:
      automatic: true
      includeLayers: true
      number: 3
    bundle:
      linting: false # Enable linting as a part of the build process
      # sourcemaps: true
      packager: yarn
      # externals:                   # Don't include these in the package
          # - chrome-aws-lambda             # Because it'll be provided through a Lambda Layer
          # - "@themarkup/blacklight-collector"
    webpack:
      webpackConfig: 'webpack.config.js'   # Name of webpack configuration file 
      includeModules: false   # Node modules configuration for packaging 
      packager: 'yarn'   # Packager that will be used to package your external modules 
      excludeFiles: src/**/*.test.js # Provide a glob for files to ignore 