service: tdcx-todo-api

plugins:
  - serverless-prune-plugin
  # - serverless-bundle
  - serverless-webpack

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  profile: ${opt:profile, 'sigmund-profile'}

functions:
  todo-api:
    handler: tdcx-todos/handler.main
    events:
        - http:
            path: api/{proxy+}
            method: ANY
            cors: true

            
custom:
    prune:
      automatic: true
      includeLayers: true
      number: 3
    bundle:
      linting: false # Enable linting as a part of the build process
      packager: yarn
    webpack:
      webpackConfig: 'webpack.config.js'   # Name of webpack configuration file 
      includeModules: false   # Node modules configuration for packaging 
      packager: 'yarn'   # Packager that will be used to package your external modules 